"""Create core schema: molecules, reactions, lineage, ontology.

Revision ID: 001
Revises: None
Create Date: 2026-03-27

Hand-written migration (not autogenerated) because RDKit mol type,
bit(2048), and HNSW/GiST indexes require raw DDL.

Assumes extensions (vector, age, rdkit, timescaledb) are already created
via docker/postgres/init.sql. If running manually, first execute:
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS rdkit;
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # Schemas (idempotent — init.sql may have already created these)
    # ------------------------------------------------------------------
    for schema in ("chem", "rxn", "onto", "ingest", "lineage"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # ------------------------------------------------------------------
    # chem.molecules
    # ------------------------------------------------------------------
    # Standard columns via op.create_table; extension-specific columns
    # (mol, fp_morgan) added via ALTER TABLE for DDL robustness.
    op.create_table(
        "molecules",
        sa.Column("inchikey", sa.Text, primary_key=True),
        sa.Column("canonical_smiles", sa.Text, nullable=False),
        sa.Column("inchi", sa.Text),
        sa.Column("mol_formula", sa.Text),
        sa.Column("mol_weight", sa.Float),
        sa.Column("exact_mass", sa.Float),
        sa.Column("logp", sa.Float),
        sa.Column("tpsa", sa.Float),
        sa.Column("hba", sa.Integer),
        sa.Column("hbd", sa.Integer),
        sa.Column("num_rotatable", sa.Integer),
        sa.Column("num_rings", sa.Integer),
        # fp_morgan_vec uses pgvector — works natively with Alembic
        sa.Column("fp_morgan_vec", Vector(2048)),
        sa.Column("sources", sa.ARRAY(sa.Text), server_default="{}"),
        sa.Column("cas_number", sa.Text),
        sa.Column("chembl_id", sa.Text),
        sa.Column("pubchem_cid", sa.BigInteger),
        sa.Column("chebi_id", sa.Text),
        sa.Column("commercially_available", sa.Boolean),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")
        ),
        schema="chem",
    )

    # Extension-specific columns via raw DDL
    op.execute("ALTER TABLE chem.molecules ADD COLUMN mol mol")
    op.execute("ALTER TABLE chem.molecules ADD COLUMN fp_morgan bit(2048)")

    # ------------------------------------------------------------------
    # rxn.reactions
    # ------------------------------------------------------------------
    op.create_table(
        "reactions",
        sa.Column("reaction_id", sa.Text, primary_key=True),
        sa.Column("reaction_smiles", sa.Text),
        sa.Column("reaction_class", sa.Text),
        sa.Column("rxno_id", sa.Text),
        sa.Column("temperature_c", sa.Float),
        sa.Column("pressure_bar", sa.Float),
        sa.Column("time_seconds", sa.Integer),
        sa.Column("atmosphere", sa.Text),
        sa.Column("yield_pct", sa.Float),
        sa.Column("yield_type", sa.Text),
        sa.Column("selectivity", sa.Text),
        sa.Column("procedure_text", sa.Text),
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("source_id", sa.Text),
        sa.Column("source_version", sa.Text),
        sa.Column("patent_id", sa.Text),
        sa.Column("doi", sa.Text),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")
        ),
        schema="rxn",
    )

    # ------------------------------------------------------------------
    # rxn.reaction_components
    # ------------------------------------------------------------------
    op.create_table(
        "reaction_components",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column(
            "reaction_id",
            sa.Text,
            sa.ForeignKey("rxn.reactions.reaction_id"),
            nullable=False,
        ),
        sa.Column(
            "inchikey",
            sa.Text,
            sa.ForeignKey("chem.molecules.inchikey"),
            nullable=False,
        ),
        sa.Column("role", sa.Text, nullable=False),
        sa.Column("stoichiometry", sa.Float),
        sa.Column("equivalents", sa.Float),
        sa.Column("mass_g", sa.Float),
        sa.Column("volume_ml", sa.Float),
        sa.Column("is_major", sa.Boolean, server_default=sa.text("TRUE")),
        sa.Column("yield_pct", sa.Float),
        sa.CheckConstraint(
            "role IN ('reactant','product','catalyst','solvent',"
            "'reagent','base','acid','ligand','additive','internal_standard')",
            name="ck_rc_role",
        ),
        sa.UniqueConstraint("reaction_id", "inchikey", "role", name="uq_rc_rxn_mol_role"),
        schema="rxn",
    )

    # ------------------------------------------------------------------
    # rxn.reaction_conditions
    # ------------------------------------------------------------------
    op.create_table(
        "reaction_conditions",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column(
            "reaction_id",
            sa.Text,
            sa.ForeignKey("rxn.reactions.reaction_id"),
            nullable=False,
        ),
        sa.Column("condition_type", sa.Text, nullable=False),
        sa.Column("value", sa.Float),
        sa.Column("unit", sa.Text, nullable=False),
        sa.Column("precision", sa.Float),
        sa.Column("phase", sa.Text),
        sa.UniqueConstraint(
            "reaction_id", "condition_type", "phase", name="uq_cond_rxn_type_phase"
        ),
        schema="rxn",
    )

    # ------------------------------------------------------------------
    # lineage.data_loads
    # ------------------------------------------------------------------
    op.create_table(
        "data_loads",
        sa.Column(
            "load_id",
            sa.Uuid,
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("source_name", sa.Text, nullable=False),
        sa.Column("source_version", sa.Text),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("status", sa.Text, server_default="running"),
        sa.Column("records_loaded", sa.Integer, server_default="0"),
        sa.Column("records_skipped", sa.Integer, server_default="0"),
        sa.Column("records_failed", sa.Integer, server_default="0"),
        sa.Column("error_log", sa.JSON),
        sa.Column("loader_version", sa.Text),
        sa.Column("config", sa.JSON),
        sa.CheckConstraint(
            "status IN ('running','completed','failed')",
            name="ck_dl_status",
        ),
        schema="lineage",
    )

    # ------------------------------------------------------------------
    # lineage.molecule_provenance
    # ------------------------------------------------------------------
    op.create_table(
        "molecule_provenance",
        sa.Column(
            "inchikey",
            sa.Text,
            sa.ForeignKey("chem.molecules.inchikey"),
            nullable=False,
        ),
        sa.Column("source_name", sa.Text, nullable=False),
        sa.Column("source_id", sa.Text),
        sa.Column(
            "load_id",
            sa.Uuid,
            sa.ForeignKey("lineage.data_loads.load_id"),
        ),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")
        ),
        sa.PrimaryKeyConstraint("inchikey", "source_name"),
        schema="lineage",
    )

    # ------------------------------------------------------------------
    # onto.reaction_classes
    # ------------------------------------------------------------------
    op.create_table(
        "reaction_classes",
        sa.Column("class_id", sa.Text, primary_key=True),
        sa.Column(
            "parent_id",
            sa.Text,
            sa.ForeignKey("onto.reaction_classes.class_id"),
        ),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("rxno_id", sa.Text),
        sa.Column("description", sa.Text),
        sa.Column("smarts_pattern", sa.Text),
        sa.Column("level", sa.Integer, nullable=False, server_default="0"),
        schema="onto",
    )

    # ------------------------------------------------------------------
    # onto.molecule_roles
    # ------------------------------------------------------------------
    op.create_table(
        "molecule_roles",
        sa.Column("role_id", sa.Text, primary_key=True),
        sa.Column(
            "parent_id",
            sa.Text,
            sa.ForeignKey("onto.molecule_roles.role_id"),
        ),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("description", sa.Text),
        schema="onto",
    )

    # ------------------------------------------------------------------
    # onto.hazard_data
    # ------------------------------------------------------------------
    op.create_table(
        "hazard_data",
        sa.Column(
            "inchikey",
            sa.Text,
            sa.ForeignKey("chem.molecules.inchikey"),
            nullable=False,
        ),
        sa.Column("ghs_codes", sa.ARRAY(sa.Text)),
        sa.Column("signal_word", sa.Text),
        sa.Column("pictograms", sa.ARRAY(sa.Text)),
        sa.Column("source", sa.Text, server_default="pubchem_ghs"),
        sa.PrimaryKeyConstraint("inchikey", "source"),
        schema="onto",
    )

    # ==================================================================
    # Indexes
    # ==================================================================

    # --- chem.molecules: extension-specific indexes (raw DDL) ---
    op.execute(
        "CREATE INDEX idx_mol_substruct ON chem.molecules USING gist(mol)"
    )
    # Note: fp_morgan_vec HNSW index skipped — pgvector 0.8.2 limits HNSW to 2000 dims
    # but Morgan fingerprints are 2048-bit. Use bit_jaccard_ops on fp_morgan instead,
    # which is the correct Tanimoto similarity metric for binary fingerprints.
    op.execute(
        "CREATE INDEX idx_fp_morgan_bit ON chem.molecules "
        "USING hnsw (fp_morgan bit_jaccard_ops)"
    )

    # --- chem.molecules: standard B-tree indexes ---
    op.create_index("idx_mol_formula", "molecules", ["mol_formula"], schema="chem")
    op.create_index(
        "idx_mol_pubchem",
        "molecules",
        ["pubchem_cid"],
        schema="chem",
        postgresql_where=sa.text("pubchem_cid IS NOT NULL"),
    )
    op.create_index(
        "idx_mol_chembl",
        "molecules",
        ["chembl_id"],
        schema="chem",
        postgresql_where=sa.text("chembl_id IS NOT NULL"),
    )

    # --- rxn.reactions indexes ---
    op.create_index("idx_rxn_class", "reactions", ["reaction_class"], schema="rxn")
    op.create_index("idx_rxn_source", "reactions", ["source"], schema="rxn")
    op.create_index(
        "idx_rxn_yield",
        "reactions",
        ["yield_pct"],
        schema="rxn",
        postgresql_where=sa.text("yield_pct IS NOT NULL"),
    )
    op.create_index(
        "idx_rxn_temp",
        "reactions",
        ["temperature_c"],
        schema="rxn",
        postgresql_where=sa.text("temperature_c IS NOT NULL"),
    )

    # --- rxn.reaction_components indexes ---
    op.create_index(
        "idx_rc_reaction", "reaction_components", ["reaction_id"], schema="rxn"
    )
    op.create_index(
        "idx_rc_molecule", "reaction_components", ["inchikey"], schema="rxn"
    )
    op.create_index("idx_rc_role", "reaction_components", ["role"], schema="rxn")


def downgrade() -> None:
    # Drop indexes (extension-specific first)
    op.execute("DROP INDEX IF EXISTS chem.idx_mol_substruct")
    op.execute("DROP INDEX IF EXISTS chem.idx_fp_morgan_hnsw")
    op.execute("DROP INDEX IF EXISTS chem.idx_fp_morgan_bit")

    # Drop tables in reverse FK dependency order
    op.drop_table("hazard_data", schema="onto")
    op.drop_table("molecule_roles", schema="onto")
    op.drop_table("reaction_classes", schema="onto")
    op.drop_table("molecule_provenance", schema="lineage")
    op.drop_table("data_loads", schema="lineage")
    op.drop_table("reaction_conditions", schema="rxn")
    op.drop_table("reaction_components", schema="rxn")
    op.drop_table("reactions", schema="rxn")
    op.drop_table("molecules", schema="chem")

    # Drop schemas
    for schema in ("lineage", "ingest", "onto", "rxn", "chem"):
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
